#!/bin/sh

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Mark Wong & Open Source Development Labss, Inc.
#

DIR=`dirname $0`
. ${DIR}/mysql_profile || exit 1

engine=`echo $MYSQL_ENGINE | tr 'A-Z' 'a-z' `

# Load tables
# This background stuff is honestly kinda ugly. IMO the right way to do this is to utilize make -j
load_table() {
    table=${1}
    if [ x${2} == x ]; then
	file=${table}.tbl
    else
	file=${2}.tbl
    fi
    if [ -f $DSS_QUERY/ddl/$engine/${table}.sql ] ; then 
	cat $DSS_QUERY/ddl/$engine/${table}.sql | mysql --defaults-file=${DEFAULTS_FILE} $DBNAME || exit 1
    else
        cat $DSS_QUERY/ddl/${table}.sql | mysql --defaults-file=${DEFAULTS_FILE} $DBNAME || exit 1
    fi
    # This disable/enable trick only works on MyISAM for the moment. 
    mysql --defaults-file=${DEFAULTS_FILE} -D $DBNAME -e "alter table $table disable keys;"
    mysqlimport --defaults-file=${DEFAULTS_FILE} --fields-terminated-by='|' ${DBNAME} ${DBDATA}/${file}
    mysql --defaults-file=${DEFAULTS_FILE} -D $DBNAME -e "alter table $table enable keys;"
}

while getopts "bd:e:" OPT; do
    case ${OPT} in
	b)
	BACKGROUND=yes
	;;
	d)
	DBDATA=${OPTARG}
	;;
	e)
	MYSQL_ENGINE=${OPTARG}
	;;
    esac
done


load_table supplier 
load_table part
load_table partsupp
load_table customer
load_table orders
load_table lineitem
load_table nation
load_table region

mysql --defaults-file=${DEFAULTS_FILE} -D ${DBNAME} -e "
CREATE TABLE time_statistics (
	task_name VARCHAR(40),
	s_time TIMESTAMP default current_timestamp,
	e_time TIMESTAMP,
	int_time INTEGER) engine=myisam;
" || exit 1

DBUSER="dbt";
mysql --defaults-file=${DEFAULTS_FILE} -D ${DBNAME} -e "
grant select on nation to ${DBUSER};
grant select on customer to ${DBUSER};
grant select on part to ${DBUSER};
grant select on partsupp to ${DBUSER};
grant select on region to ${DBUSER};
grant select,insert,update,delete on lineitem to ${DBUSER};
grant select,insert,update,delete on orders to ${DBUSER};
grant select,insert,update,delete on time_statistics to ${DBUSER};
" || exit 1

wait

exit 0
