#!/bin/sh

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Mark Wong & Open Source Development Labss, Inc.
#

DIR=`dirname $0`
. ${DIR}/mysql_profile || exit 1

engine=`echo $MYSQL_ENGINE | tr 'A-Z' 'a-z' `

# Create tables
create_table() {
    table=${1}
    if [ -f $DSS_QUERY/ddl/$engine/${table}.sql ] ; then 
	cat $DSS_QUERY/ddl/$engine/${table}.sql | mysql --defaults-file=${DEFAULTS_FILE} $DBNAME || exit 1
    else
        cat $DSS_QUERY/ddl/${table}.sql | mysql --defaults-file=${DEFAULTS_FILE} $DBNAME || exit 1
    fi
}

while getopts "bd:e:" OPT; do
    case ${OPT} in
	b)
	BACKGROUND=yes
	;;
	d)
	DBDATA=${OPTARG}
	;;
	e)
	MYSQL_ENGINE=${OPTARG}
	;;
    esac
done


create_table supplier 
create_table part
create_table partsupp
create_table customer
create_table orders
create_table lineitem
create_table nation
create_table region

mysql --defaults-file=${DEFAULTS_FILE} -D ${DBNAME} -e "
CREATE TABLE time_statistics (
	task_name VARCHAR(40),
	s_time TIMESTAMP default current_timestamp,
	e_time TIMESTAMP,
	int_time INTEGER);
" || exit 1

DBUSER="dbt";
mysql --defaults-file=${DEFAULTS_FILE} -D ${DBNAME} -e "
grant select on nation to ${DBUSER};
grant select on customer to ${DBUSER};
grant select on part to ${DBUSER};
grant select on partsupp to ${DBUSER};
grant select on region to ${DBUSER};
grant select,insert,update,delete on lineitem to ${DBUSER};
grant select,insert,update,delete on orders to ${DBUSER};
grant select,insert,update,delete on time_statistics to ${DBUSER};
" || exit 1

wait

exit 0
