#!/bin/bash

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2006 Open Source Development Labs, Inc.
#               2006-2010 Mark Wong
#

DIR=`dirname $0`
. ${DIR}/mysql_profile || exit 1

echo -n "Starting MySQL..."

if [ "x" = "x${MYDATA}" ]; then
	echo "ERROR: MYDATA must be set"
	exit 1
fi

LOGFILE="dbt3.log"
OUTDIR="."
HOSTNAME=`hostname`

if [ ! -z $DEFAULTS_FILE ]; then
	DEFAULTS_FILE_ARG="--defaults-file=${DEFAULTS_FILE}"
fi;

while getopts "fo:p:s:" OPT; do
	case ${OPT} in
	f)
		if [ -f "${MYDATA}/${HOSTNAME}.pid" ]; then
			rm ${MYDATA}/${HOSTNAME}.pid
		fi
		;;
	o)
		OUTDIR=$OPTARG
		;;
	p)
		DEFAULTS_FILE=${OPTARG}
		DEFAULTS_FILE_ARG="--defaults-file=${DEFAULTS_FILE}"
		;;
	esac
done

if [ -f "${MYDATA}/${HOSTNAME}.pid" ]; then
	echo "MySQL pid file '${MYDATA}/${HOSTNAME}.pid' already exists."
	exit 1
fi
nohup mysqld_safe ${DEFAULTS_FILE_ARG} \
		--log-error=${OUTDIR}/${LOGFILE} > /dev/null 2>&1 &
sleep 10

echo "done."

exit 0
