#!/bin/bash

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Rod Taylor & Open Source Development Lab, Inc.
#

DIR=`dirname $0`
. ${DIR}/pgsql_profile || exit 1

if [ -z ${PGDATA} ]; then
	echo "PGDATA not defined."
	exit 1
fi

if [ ${USE_HYPER} -eq 1 ]; then
	PG_CTL=hyper_ctl
	PIDFILE=${PGDATA}/hyperd.pid
else
	PG_CTL=pg_ctl
	PIDFILE=${PGDATA}/postmaster.pid
fi

LOGFILE="dbt3.log"
OUTDIR="."
USE_PG_AUTOVACUUM=0
while getopts "afo:p:" OPT; do
	case ${OPT} in
        a)
                USE_PG_AUTOVACUUM=1
                ;;
	f)
		rm -f ${PGDATA}/postmaster.pid
		;;
	o)
		OUTDIR=${OPTARG}
		;;
	p)
		PARAMETERS="${OPTARG}"
		;;
	esac
done

if [ -f "${PIDFILE}" ]; then
	echo "Database is already started: ${PIDFILE}"
	exit 0
fi

sleep 1

if [ "x${PGPORT}" != "x" ]; then
	PARAMETERS="${PARAMETERS} -p ${PGPORT}"
fi

if [ "x${PARAMETERS}" = "x" ]; then
        ${PG_CTL} -D ${PGDATA} -l ${OUTDIR}/${LOGFILE} start
else
	${PG_CTL} -D ${PGDATA} -o "${PARAMETERS}" -l ${OUTDIR}/${LOGFILE} start
fi

sleep 10

if [ ! -f "${PIDFILE}" ]; then
	echo "database did not start correctly, check database log"
	exit 1
fi

exit 0
