#!/bin/sh

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Mark Wong & Open Source Development Labs, Inc.
#

DIR=`dirname $0`
. ${DIR}/pgsql_profile || exit 1

if [ "x${DBNAME}" = "x" ]; then
    echo "DBNAME not defined."
    exit 1
fi

while getopts "l:" OPT; do
	case ${OPT} in
	l)
		PORT=${OPTARG}
		;;
	esac
done

if [ ! "x${PORT}" = "x" ]; then
	PORTARG="-p ${PORT}"
fi
PSQL="psql ${PORTARG} -e -d ${DBNAME}"

# need to consider table dependencies.
${PSQL} -e -d $SID -c "DROP TABLE supplier;"
${PSQL} -e -d $SID -c "DROP TABLE part;"
${PSQL} -e -d $SID -c "DROP TABLE partsupp;"
${PSQL} -e -d $SID -c "DROP TABLE customer;"
${PSQL} -e -d $SID -c "DROP TABLE orders;"
${PSQL} -e -d $SID -c "DROP TABLE lineitem;"
${PSQL} -e -d $SID -c "DROP TABLE nation;"
${PSQL} -e -d $SID -c "DROP TABLE region;"
${PSQL} -e -d $SID -c "DROP TABLE time_statistics;"
