#!/bin/sh

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Mark Wong & Open Source Development Labs, Inc.
#

DIR=`dirname $0`
. ${DIR}/pgsql_profile || exit 1

if [ "x${DBNAME}" = "x" ]; then
	echo "DBNAME not defined."
	exit 1
fi

while getopts "l:o:" opt; do
	case $opt in
        l)
                PORT=${OPTARG}
                ;;
	o)
		OUTPUT=$OPTARG
		;;
	esac
done

if [ "$OUTPUT" == "" ]; then
	echo "use -o and specify the backup file"
	exit 1;
fi

if [ ! "x${PORT}" = "x" ]; then
        PORTARG="-p ${PORT}"
fi

_test=`pg_dump ${PORTARG} -Fc $DBNAME --file=$OUTPUT | grep OK`
if [ "$_test" != "" ]; then
	echo "backup failed: $_test"
	exit 1
fi

exit 0
